### ISSUE TITLE
Set up Trial Period deployment/Heroku node

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#121]
* @channel : Spoke with @jasnow1 and we think the app seems usable, but could benefit from a 24-hour trial period where a few people can try out the app and offer any feedback. Definitely would be good to have the designers trying it out and maybe some other parties. What do we think?
* Also have multiple people try it out during trial period
* @cmuld3r: "real users" - more like friends or others in Slack
* From @cmuld3r ok should we all sign up in one area?
* @cmuld3r: I would run the Trial period on production because staging may change on each commit (too volatile). We can reset production database at end of trail before going GA.

**Comment by PepperTeasdale** [comment]
Have had a few friends poking around.

**Comment by jasnow** [comment]
@PepperTeasdale - Any comments from your friends?

**Comment by cmuld3r** [comment]
some of my notes:
- on mobile "send email confirmation" on the signup page gets cutoff. we could change it to "confirm email"
- when going back to the user profile and editing, do we want a 'cancel' button to return to the host/travel index page without saving the profile?
- the back button when on a host/travel record reads 'HOME'... but we already have a 'HOME' back button which goes back to the home page from the profile. change the one on the host/travel record to 'BACK' instead of 'HOME'
- how about 'info@berniebnb.com' as web address? any justification for using another one? and i think @PepperTeasdale mentioned this, but are we thinking of setting up an email forward or mailbox for it?
- add another 'submit feedback' accessible to hosts, possibly just on the host/travel index page

**Comment by cmuld3r** [comment]
and by signup in one area, i meant, should we all sign up near a certain zip to get more records to play with? which zips did you use?

**Comment by cmuld3r** [comment]
we should probably open it to codersforsanders for testing as well

**Comment by PepperTeasdale** [comment]
One of them said he left a comment on the google form, but I'm not seeing it on the spreadsheet. I wonder if he just didn't submit, since it seems to work for everyone else.
His comments to me:
* Would it be possible to not give personal details when contacting a host and just have their emails sent 
  through the system (eg craigslist)?
* Zipcode error message shows up twice.
* On mobile, the buttons take up the whole width of the screen, which looks kind of funny to him.
  Not sure if this is a design choice or a styling error.

**Comment by PepperTeasdale** [comment]
I like that idea of using coders for sanders. I have visits and hostings in St Louis, MO, Brooklyn, NY, and Beverly Hills, CA (famous zipcode)

**Comment by cmuld3r** [comment]
oh, also:
- we can put the new logo on the 'host/travel index page' (/users/show.html.haml) along with the feedback button mentioned before

**Comment by cmuld3r** [comment]
is berniebnb.com the place to test? is it updated with the latest and ready to release to codersforsanders?

**Comment by PepperTeasdale** [comment]
I'm going to add that second submit feedback button really quick.

**Comment by jasnow** [comment]
Here are the issues I saw from above (https://sites.google.com/site/bbnbtrialissues). Note that I created a "tag" for each one - such as "Chris/a", "Justin/c".

**Comment by PepperTeasdale** [comment]
Feedback is coming in and I am making new issues based on that.
