### ISSUE TITLE
Add timezone to users

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#202]
Per @jake3030 's recommendation, I would like to add a timezone column to users and store time-related data in UTC. I found this article on the subject:
https://robots.thoughtbot.com/its-about-time-zones

**Comment by jake3030** [comment]
I am copying this from the pull request #199 here:
@PepperTeasdale: Thanks @jake3030 ! So you update the user's timezone column whenever they sign in from a different time zone? I like the idea and am interested in implementing it.

@jake3030: ya, thats one way.  normally, the user would just set it via their settings
page or whatever, but if we have users traveling and making hostings then
we would need to change it.

I still havent played with the app yet bcs I havent gotten the omniauth creds setup so I still dont know exactly how the app works.  I just finished reading through some of the documentation and had a cursory glance at the code and I think the place for the TZ column is on the hosting itself.  This is where we care about what time something is happening at.  The visits can use the column for their calculations since a visit cannot exist without a hosting (i'm assuming, i have yet to read thru all the code).  We dont really care about the user's TZ in general, we care about the place's timezone.

My example was for an app that the user needs to read everything in their TZ, but our case involves the place's TZ and not the user's.  Like a hotel basically.


What do you guys think?



Is that what happens?  Do people that host an event have multiple places to
host in different time zones?

**Comment by jasnow** [comment]
@jake3030 - Would you like to join our Slack channel? Is the emailed that ends with this, "flvorful.com", your best email? If not, you can find my email on my Github home page to send me a better email.

**Comment by jasnow** [comment]
Anything else?

**Comment by PepperTeasdale** [comment]
#208 took care of the troubles we were having. Since time zones don't really play a big part in the app, I am closing this issue.
