### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#267]
We could possibly have a footer with links to a contact page and faq page. This seems like the most logical entry point to these pages. If someone has a better idea, please share here.

**Comment by jasnow** [comment]
@cockroachbill - Are you still going to do this?

**Comment by jasnow** [comment]
@PepperTeasdale and @cockroachbill - Is this issue done?

**Comment by jasnow** [comment]
Is this done? I see the footer locally and in staging

**Comment by jasnow** [comment]
Checked locally. See 6 things in the footer:
 * (c) BernieBNB 2016 (static)
 * Twitter icon **(DOES NOT WORK)**
 * Facebook icon **(DOES NOT WORK)**
 * Instagram icon **(DOES NOT WORK)**
 * "Privary Policy" link (works)
 * FAQ link (works)

**Comment by jasnow** [comment]
Now have a fix for the above 3 icons.

**Comment by jasnow** [comment]
* Asked on Slack: Do we want them to go to the main page for each provider (Facebook, Linkedin, Twitter) or some subpage?
 * Answer: I think we don't need those. I'm not sure what they would be for since we don't have an active account with those services
 * so just delete them?
 * Answer: I think so
 * SO I did
